services:
    cli:
        container_name: cli
        build:
            context: ./.docker
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
